//! # Auto-generated
//!
//! This file was generated by a build script.
//!
//! The build script monitors this file and regenerates it on changes.
//! Manual modifications will be lost.
//!
//! # Content
//!
//! Holds encoders for instructions valid in both 32 and 64-bit modes.
#![allow(non_snake_case)]
#![allow(unused_imports)]

use crate::encoding::utils;
use crate::models::{EncodedX86_64Instruction, GPROrMemory, Immediate8, Immediate16, Immediate32};

/// No operation.
#[inline(always)]
pub const fn encode_nop() -> EncodedX86_64Instruction {
    unsafe { EncodedX86_64Instruction::from_array([0x90]) }
}

/// Lock prefix used for atomic operations.
#[inline(always)]
pub const fn encode_lock() -> EncodedX86_64Instruction {
    unsafe { EncodedX86_64Instruction::from_array([0xF0]) }
}

/// Add imm8 to AL.
#[inline(always)]
pub const fn encode_add_AL_imm8(imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { utils::enc_I::encode_I_imm8([0x04], imm8) }
}

/// Add imm16 to AX.
#[inline(always)]
pub const fn encode_add_AX_imm16(imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { utils::enc_I::encode_I_imm16_operand_size_override([0x05], imm16) }
}

/// Add imm32 to EAX.
#[inline(always)]
pub const fn encode_add_EAX_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { utils::enc_I::encode_I_imm32([0x05], imm32) }
}

/// Add imm32 sign-extended to RAX.
#[inline(always)]
pub const fn encode_add_RAX_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { utils::enc_I::encode_I_imm32_prefix_rex_w([0x05], imm32) }
}

/// Add imm8 to memory or 8-bit register.
#[inline(always)]
pub const fn encode_add_rm8_imm8(rm8: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { utils::enc_MI::encode_MI_rm8_imm8([0x80], 0x00, rm8, imm8) }
}

/// Return to calling procedure.
#[inline(always)]
pub const fn encode_ret() -> EncodedX86_64Instruction {
    unsafe { EncodedX86_64Instruction::from_array([0xC3]) }
}

/// Return to calling procedure and pop imm16 bytes from stack.
#[inline(always)]
pub const fn encode_ret_imm16(imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { utils::enc_I::encode_I_imm16([0xC2], imm16) }
}
