//! # Auto-generated
//!
//! This file was generated by a build script.
//!
//! The build script monitors this file and regenerates it on changes.
//! Manual modifications will be lost.
//!
//! # Content
//!
//! Holds encoders for instructions valid in 32-bit mode only.
#![allow(non_snake_case)]
#![allow(unused_imports)]

use crate::encoding::utils;
use crate::models::{EncodedX86Instruction, Immediate8, Immediate16, Immediate32};
