//! # Auto-generated
//!
//! This file was generated by a build script.
//!
//! The build script monitors this file and regenerates it on changes.
//! Manual modifications will be lost.
//!
//! # Content
//!
//! Holds encoders for instructions valid in 64-bit mode only.
#![allow(non_snake_case)]
#![allow(unused_imports)]

use crate::encoding::utils;
use crate::models::{EncodedX86Instruction, Immediate8, Immediate16, Immediate32};

/// Add imm32 sign-extended to RAX.
#[inline(always)]
pub const fn encode_add_RAX_imm32(imm32: Immediate32) -> EncodedX86Instruction {
    unsafe { utils::enc_I::encode_I_imm32_prefix_rex_w([0x05], imm32) }
}
