//! # Auto-generated
//!
//! This file was generated by a build script.
//!
//! The build script monitors this file and regenerates it on changes.
//! Manual modifications will be lost.
mod mnemonics_gen;
pub use mnemonics_gen::*;

// The following three modules will be reexported in the
// corresponding non-ext modules.
mod bit32_gen;
mod bit64_gen;
mod universal_gen;

pub mod bit32;
pub mod bit64;
pub mod universal;
