//! # Auto-generated
//!
//! This file was generated by a build script.
//!
//! The build script monitors this file and regenerates it on changes.
//! Manual modifications will be lost.

use crate::{
    encoding::utils::group1,
    models::{EncodedX86Instruction, GPR, Immediate16, Immediate32},
};

/// # Safety
///
/// This function is unsafe because it doesn't validate GPR size.
/// It panics in debug mode, but not in release. The behaviour
/// is undefined in release mode.
#[inline(always)]
pub const unsafe fn encode_add_r16_imm16(r16: GPR, imm16: Immediate16) -> EncodedX86Instruction {
    unsafe { group1::encode_group1_r16_imm16(0x81, 0x00, r16, imm16) }
}

/// # Safety
///
/// This function is unsafe because it doesn't validate GPR size.
/// It panics in debug mode, but not in release. The behaviour
/// is undefined in release mode.
#[inline(always)]
pub const unsafe fn encode_add_r32_imm32(r32: GPR, imm32: Immediate32) -> EncodedX86Instruction {
    unsafe { group1::encode_group1_r32_imm32(0x81, 0x00, r32, imm32) }
}
