#![allow(clippy::write_with_newline, clippy::unused_self, clippy::unnecessary_wraps)]
use std::{error::Error, fmt::Write, fs::OpenOptions, path::PathBuf};

use std::io::Write as _;

use _osom_encoders_x86_64_doc::{FlagId, InstructionGroup, InstructionVariant, OperandEncodingId, OperandId, X86Doc};

pub struct Generator {
    target_dir: PathBuf,
    doc: X86Doc,
}

const ENCODERS_DIR: &str = "encoders";
const GEN_INFO: &str = "// ** This file is automatically generated from x86.yaml schema. Do not modify! **\n\n";

impl Generator {
    pub fn new(target_dir: PathBuf) -> Self {
        let mut doc = X86Doc::create();
        doc.instruction_groups.sort_by_key(|group| group.id);
        for group in &mut doc.instruction_groups {
            group.variants.sort_by_key(|variant| variant.id);
        }
        Self { target_dir, doc }
    }

    pub fn generate(self) -> Result<(), Box<dyn Error>> {
        self.generate_encoders()?;
        Ok(())
    }

    fn generate_encoders(&self) -> Result<(), Box<dyn Error>> {
        let encoders_dir = self.target_dir.join(ENCODERS_DIR);
        println!("Generating encoders to {}", encoders_dir.display());

        if encoders_dir.exists() {
            std::fs::remove_dir_all(&encoders_dir)?;
        }
        std::fs::create_dir_all(&encoders_dir)?;

        self.generate_encoders_mod()?;

        for group in &self.doc.instruction_groups {
            self.generate_encoder_file(group)?;
        }

        self.update_nop_file()?;
        Ok(())
    }

    fn generate_encoders_mod(&self) -> Result<(), Box<dyn Error>> {
        let encoders_lib_file = self.target_dir.join(ENCODERS_DIR).join("mod.rs");

        println!(">>> Generating {}", encoders_lib_file.display());

        let mut content = String::new();
        let _ = write!(
            content,
            "//! This module contains the encoders for the `X86_64` instruction set.\n\n"
        );
        let _ = write!(content, "{GEN_INFO}");
        for group in &self.doc.instruction_groups {
            let _ = write!(content, "pub mod {};\n", group.name);
        }

        std::fs::write(encoders_lib_file, content)?;

        Ok(())
    }

    fn generate_encoder_file(&self, group: &InstructionGroup) -> Result<(), Box<dyn Error>> {
        let encoder_file = self.target_dir.join(ENCODERS_DIR).join(format!("{}.rs", group.name));
        println!(">>> Generating {}", encoder_file.display());

        let mut content = String::new();

        let _ = write!(
            content,
            "//! This module contains the encoders for the `{}` instruction group.\n",
            group.name
        );
        let _ = write!(content, "#![allow(unused_imports)]\n\n");
        let _ = write!(content, "{GEN_INFO}");
        let _ = write!(content, "use crate::models::{{\n");
        let _ = write!(content, "    EncodedX86_64Instruction, GPR, GPROrMemory, Memory,\n");
        let _ = write!(content, "    Immediate8, Immediate16, Immediate32, Immediate64,\n");
        let _ = write!(content, "    Offset, Scale, Size,\n");
        let _ = write!(content, "}};\n\n");
        for variant in &group.variants {
            let _ = write!(content, "{}", self.generate_variant_file(variant)?);
        }
        content.push('\n');
        std::fs::write(encoder_file, content)?;
        Ok(())
    }

    fn generate_variant_file(&self, variant: &InstructionVariant) -> Result<String, Box<dyn Error>> {
        let mut content = String::new();
        let unique_name = variant.get_unique_name().to_lowercase();
        let fn_name = if unique_name.is_empty() {
            "encode"
        } else {
            &format!("encode_{unique_name}")
        };

        let partial_encoder_name = generate_partial_encoder_name(variant);

        let passed_args = generate_passed_args(variant);

        let mut args = Vec::new();
        for operand in &variant.operands {
            let op_name = <&'static str>::from(operand).to_lowercase();
            let op_type = map_operand_to_type(operand);
            args.push(format!("{op_name}: {op_type}"));
        }
        let args = args.join(", ");

        let _ = write!(content, "/// {}\n", variant.description);
        let _ = write!(content, "///\n");
        let _ = write!(content, "/// # Safety\n");
        let _ = write!(content, "///\n");
        if variant.operands.is_empty() {
            let _ = write!(
                content,
                "/// This function is safe to call. It is marked as unsafe for consistency with other encoders.\n"
            );
        } else {
            let _ = write!(
                content,
                "/// It is the caller's responsibility to ensure that the operands are valid.\n"
            );
            let _ = write!(content, "/// Otherwise the behavior is undefined.\n");
        }
        let _ = write!(content, "#[inline]\n");
        let _ = write!(
            content,
            "pub const unsafe fn {fn_name}({args}) -> EncodedX86_64Instruction {{\n"
        );
        let op_enc = <&'static str>::from(variant.operand_encoding.clone()).to_lowercase();
        let _ = write!(content, "    unsafe {{\n");
        let _ = write!(
            content,
            "        crate::partial_encoders::{op_enc}::{partial_encoder_name}({passed_args})\n"
        );
        let _ = write!(content, "    }}\n");
        let _ = write!(content, "}}\n\n");
        Ok(content)
    }

    fn update_nop_file(&self) -> Result<(), Box<dyn Error>> {
        let content = "
/// Represents length for NOP instruction. Internally this is `u8`
/// but with values in `0..=9` range.
#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy)]
#[repr(transparent)]
#[must_use]
pub struct NopLength {
    len: u8,
}

/// Represents the length out of range error. This happens whenever
/// the NOP instruction is outside of `0..=9` range.
#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy)]
#[repr(transparent)]
#[must_use]
pub struct NopLengthOutOfRange {
    phantom: core::marker::PhantomData<()>,
}

impl NopLength {
    /// Creates a new [`NopLength`].
    ///
    /// # Errors
    ///
    /// Returns [`NopLengthOutOfRange`] if `len > 9`.
    #[inline]
    pub const fn new(len: u8) -> Result<Self, NopLengthOutOfRange> {
        if len > 9 {
            return Err(NopLengthOutOfRange {
                phantom: core::marker::PhantomData,
            });
        }

        Ok(unsafe { Self::new_unchecked(len) })
    }

    /// Creates a new [`NopLength`].
    ///
    /// # Safety
    ///
    /// It is up to the caller to ensure that `len <= 9`.
    #[inline(always)]
    pub const unsafe fn new_unchecked(len: u8) -> Self {
        Self { len }
    }

    /// Returns the internal length.
    #[must_use]
    #[inline(always)]
    pub const fn as_u8(self) -> u8 {
        self.len
    }
}

impl TryFrom<u8> for NopLength {
    type Error = NopLengthOutOfRange;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<NopLength> for u8 {
    fn from(value: NopLength) -> Self {
        value.len
    }
}

/// No operation with a given length.
///
/// # Notes
/// 
/// * The [`encode_with_len(0)`][encode_with_len] call returns an empty instruction (of length 0).
/// * The [`encode_with_len(1)`][encode_with_len] call is equivalent to [`encode()`] call. Except
///   it is slightly less efficient.
/// * The [`encode_with_len(n)`][encode_with_len] call returns an instruction of length `n`.
/// 
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[allow(clippy::missing_panics_doc)]
pub const unsafe fn encode_with_len(len: NopLength) -> EncodedX86_64Instruction {
    use crate::partial_encoders::zo::encode;
    unsafe {
        match len.as_u8() {
            0 => EncodedX86_64Instruction::new(),
            1 => encode([0x90]),
            2 => encode([0x66, 0x90]),
            3 => encode([0x0F, 0x1F, 0x00]),
            4 => encode([0x0F, 0x1F, 0x40, 0x00]),
            5 => encode([0x0F, 0x1F, 0x44, 0x00, 0x00]),
            6 => encode([0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00]),
            7 => encode([0x0F, 0x1F, 0x80, 0x00, 0x00, 0x00, 0x00]),
            8 => encode([0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00]),
            9 => encode([0x66, 0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00]),
            _ => panic!(\"Invalid length for encode_with_len call. Expected u8 in 1..=9 range.\"),
        }
    }
}
"
        .trim();

        let encoder_file = self.target_dir.join(ENCODERS_DIR).join("nop.rs");

        let mut file = OpenOptions::new()
            .append(true)
            .create(false)
            .open(encoder_file)
            .unwrap();

        file.write_all(content.as_bytes())?;
        Ok(())
    }
}

fn map_operand_to_type(operand: &OperandId) -> &'static str {
    match operand {
        OperandId::Imm8 => "Immediate8",
        OperandId::Imm16 => "Immediate16",
        OperandId::Imm32 => "Immediate32",
        OperandId::Imm64 => "Immediate64",
        OperandId::RM8 | OperandId::RM16 | OperandId::RM32 | OperandId::RM64 => "GPROrMemory",
        OperandId::Reg8 | OperandId::Reg16 | OperandId::Reg32 | OperandId::Reg64 => "GPR",
        OperandId::Mem64 => "Memory",
    }
}

#[allow(clippy::single_match_else)]
fn generate_passed_args(variant: &InstructionVariant) -> String {
    let opcode = match variant.operand_encoding {
        OperandEncodingId::OI => {
            assert!(
                variant.primary_opcode.len() == 1,
                "Opcode for OI encoding must be 1 byte long."
            );
            format!("0x{:02X}", variant.primary_opcode[0])
        }
        _ => {
            let mut opcode = Vec::with_capacity(variant.primary_opcode.len());
            for x in &variant.primary_opcode {
                opcode.push(format!("0x{x:02X}"));
            }
            format!("[{}]", opcode.join(", "))
        }
    };

    let mut passed_args = Vec::with_capacity(variant.operands.len() + 1);
    passed_args.push(opcode);

    if let Some(extended_opcode) = variant.extended_opcode {
        passed_args.push(format!("0x{extended_opcode:02X}"));
    }

    let has_oso = bool_to_string(variant.flags.contains(&FlagId::OSO));
    let has_rex_w = bool_to_string(variant.flags.contains(&FlagId::RexW));

    match variant.operand_encoding {
        OperandEncodingId::MR => {
            assert!(variant.operands.len() == 2, "MR encoding must have exactly 2 operands.");
            let mut operand0 = variant.operands[0].clone();
            let mut operand1 = variant.operands[1].clone();

            assert!(
                is_gpr(&operand0) || is_gpr(&operand1),
                "One of the operands in MR encoding has to be GPR."
            );
            if is_gpr(&operand0) {
                std::mem::swap(&mut operand0, &mut operand1);
            }
            assert!(
                is_gpr_or_memory(&operand0) || operand0 == OperandId::Mem64,
                "The other MR encoding operand has to be Reg/Mem."
            );

            let op0_name = <&'static str>::from(operand0.clone()).to_lowercase();
            let op1_name = <&'static str>::from(operand1.clone()).to_lowercase();

            passed_args.push(op0_name);
            passed_args.push(op1_name);
        }
        OperandEncodingId::M => {
            assert!(variant.operands.len() == 1, "M encoding must have exactly 1 operand.");
            assert!(
                variant.extended_opcode.is_some(),
                "M encoding must have an extended opcode."
            );
            let operand0 = variant.operands[0].clone();
            let op_name = <&'static str>::from(operand0).to_lowercase();
            passed_args.push(op_name);
            passed_args.push(has_rex_w.to_string());
            passed_args.push(has_oso.to_string());
        }
        _ => {
            for operand in &variant.operands {
                let op_name = <&'static str>::from(operand).to_lowercase();
                passed_args.push(op_name);
            }
        }
    }

    passed_args.join(", ")
}

fn is_gpr_or_memory(operand: &OperandId) -> bool {
    matches!(
        operand,
        OperandId::RM8 | OperandId::RM16 | OperandId::RM32 | OperandId::RM64
    )
}

fn is_gpr(operand: &OperandId) -> bool {
    matches!(
        operand,
        OperandId::Reg8 | OperandId::Reg16 | OperandId::Reg32 | OperandId::Reg64
    )
}

fn generate_partial_encoder_name(variant: &InstructionVariant) -> String {
    let unique_name = variant.get_unique_name().to_lowercase();
    let fn_name = if unique_name.is_empty() {
        "encode"
    } else {
        &format!("encode_{unique_name}")
    };

    match variant.operand_encoding {
        OperandEncodingId::I => {
            assert!(variant.operands.len() == 1, "I encoding must have exactly 1 operand.");
            let operand = &variant.operands[0];
            let op_name = <&'static str>::from(operand).to_lowercase();

            let suffix = if variant.flags.contains(&FlagId::RexW) {
                "_rexw"
            } else if variant.flags.contains(&FlagId::OSO) {
                "_oso"
            } else {
                ""
            };

            format!("encode_{op_name}{suffix}")
        }
        OperandEncodingId::MR => {
            assert!(variant.operands.len() == 2, "MR encoding must have exactly 2 operands.");
            let operand0 = variant.operands[0].clone();
            let operand1 = variant.operands[1].clone();

            if operand0 == OperandId::Mem64 || operand1 == OperandId::Mem64 {
                assert!(
                    is_gpr(&operand0) || is_gpr(&operand1),
                    "MR encoding containg Mem64 operand must have other operand as GPR."
                );
                return "encode_mem".to_string();
            }

            "encode".to_string()
        }
        OperandEncodingId::M => "encode_gpr_or_memory".to_string(),
        _ => fn_name.to_string(),
    }
}

fn bool_to_string(bool: bool) -> &'static str {
    if bool { "true" } else { "false" }
}
