//! # Auto-generated
//!
//! This file was generated by a build script.
//!
//! The build script monitors this file and regenerates it on changes.
//! Manual modifications will be lost.
#![allow(non_camel_case_types)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InvalidMnemonicError;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
#[must_use]
pub enum Mnemonic {
    nop = 1,
    lock = 2,
    mov = 3,
    add = 4,
    cmp = 5,
    jmp = 6,
    jcc = 7,
    ret = 8,
}

impl Mnemonic {
    #[inline]
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::nop => "nop",
            Self::lock => "lock",
            Self::mov => "mov",
            Self::add => "add",
            Self::cmp => "cmp",
            Self::jmp => "jmp",
            Self::jcc => "jcc",
            Self::ret => "ret",
        }
    }

    #[inline]
    pub fn from_str(text: &str) -> Result<Self, InvalidMnemonicError> {
        match text {
            "nop" => Ok(Self::nop),
            "lock" => Ok(Self::lock),
            "mov" => Ok(Self::mov),
            "add" => Ok(Self::add),
            "cmp" => Ok(Self::cmp),
            "jmp" => Ok(Self::jmp),
            "jcc" => Ok(Self::jcc),
            "ret" => Ok(Self::ret),

            _ => Err(InvalidMnemonicError),
        }
    }
}

const _: () = const {
    assert!(
        size_of::<InvalidMnemonicError>() == 0,
        "InvalidMnemonicError must be 0 bytes."
    );
    assert!(size_of::<Mnemonic>() == 1, "Mnemonic must be 1 byte.");
    assert!(size_of::<Option<Mnemonic>>() == 1, "Option<Mnemonic> must be 1 byte.");
};
