//! # Auto-generated
//!
//! This file was generated by a build script.
//!
//! The build script monitors this file and regenerates it on changes.
//! Manual modifications will be lost.
#![allow(non_camel_case_types)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InvalidMnemonicError;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
#[must_use]
pub enum Mnemonic {
    nop = 1,
    lock = 2,
    cpuid = 3,
    ret = 4,
    mov = 5,
    lea = 6,
    add = 7,
    sub = 8,
    xor = 9,
    cmp = 10,
    jmp = 11,
    jcc = 12,
    call = 13,
}

impl Mnemonic {
    #[inline]
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::nop => "nop",
            Self::lock => "lock",
            Self::cpuid => "cpuid",
            Self::ret => "ret",
            Self::mov => "mov",
            Self::lea => "lea",
            Self::add => "add",
            Self::sub => "sub",
            Self::xor => "xor",
            Self::cmp => "cmp",
            Self::jmp => "jmp",
            Self::jcc => "jcc",
            Self::call => "call",
        }
    }

    #[inline]
    pub fn from_str(text: &str) -> Result<Self, InvalidMnemonicError> {
        match text {
            "nop" => Ok(Self::nop),
            "lock" => Ok(Self::lock),
            "cpuid" => Ok(Self::cpuid),
            "ret" => Ok(Self::ret),
            "mov" => Ok(Self::mov),
            "lea" => Ok(Self::lea),
            "add" => Ok(Self::add),
            "sub" => Ok(Self::sub),
            "xor" => Ok(Self::xor),
            "cmp" => Ok(Self::cmp),
            "jmp" => Ok(Self::jmp),
            "jcc" => Ok(Self::jcc),
            "call" => Ok(Self::call),

            _ => Err(InvalidMnemonicError),
        }
    }
}

const _: () = const {
    assert!(
        size_of::<InvalidMnemonicError>() == 0,
        "InvalidMnemonicError must be 0 bytes."
    );
    assert!(size_of::<Mnemonic>() == 1, "Mnemonic must be 1 byte.");
    assert!(size_of::<Option<Mnemonic>>() == 1, "Option<Mnemonic> must be 1 byte.");
};
