//! This module contains the encoders for the `call` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Call to RIP-relative address.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm32([0xE8], imm32) }
}

/// Call to address in 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64(rm64: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::m::encode_gpr_or_memory([0xFF], 0x02, rm64, false, false) }
}
