//! This module contains the encoders for the `cmp` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Compare 8-bit immediate with AL register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_al_imm8(imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm8([0x3C], imm8) }
}

/// Compare 16-bit immediate with AX register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_ax_imm16(imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm16_oso([0x3D], imm16) }
}

/// Compare 32-bit immediate with EAX register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_eax_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm32([0x3D], imm32) }
}

/// Compare 32-bit immediate sign-extended with RAX register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rax_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm32_rexw([0x3D], imm32) }
}

/// Compare 8-bit immediate with 8-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm8_imm8(rm8: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm8_imm8([0x80], 0x07, rm8, imm8) }
}

/// Compare 16-bit immediate with 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_imm16(rm16: GPROrMemory, imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm16_imm16([0x81], 0x07, rm16, imm16) }
}

/// Compare 32-bit immediate with 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_imm32(rm32: GPROrMemory, imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm32_imm32([0x81], 0x07, rm32, imm32) }
}

/// Compare 32-bit immediate with 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_imm32(rm64: GPROrMemory, imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm64_imm32([0x81], 0x07, rm64, imm32) }
}

/// Compare 8-bit immediate (sign-extended) with 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_imm8(rm16: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm16_imm8([0x83], 0x07, rm16, imm8) }
}

/// Compare 8-bit immediate (sign-extended) with 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_imm8(rm32: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm32_imm8([0x83], 0x07, rm32, imm8) }
}

/// Compare 8-bit immediate (sign-extended) with 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_imm8(rm64: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm64_imm8([0x83], 0x07, rm64, imm8) }
}

/// Compare 8-bit register with 8-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm8_reg8(rm8: GPROrMemory, reg8: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x38], rm8, reg8) }
}

/// Compare 16-bit register with 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_reg16(rm16: GPROrMemory, reg16: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x39], rm16, reg16) }
}

/// Compare 32-bit register with 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_reg32(rm32: GPROrMemory, reg32: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x39], rm32, reg32) }
}

/// Compare 64-bit register with 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_reg64(rm64: GPROrMemory, reg64: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x39], rm64, reg64) }
}

/// Compare 8-bit register or memory with 8-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg8_rm8(reg8: GPR, rm8: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x3A], rm8, reg8) }
}

/// Compare 16-bit register or memory with 16-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg16_rm16(reg16: GPR, rm16: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x3B], rm16, reg16) }
}

/// Compare 32-bit register or memory with 32-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg32_rm32(reg32: GPR, rm32: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x3B], rm32, reg32) }
}

/// Compare 64-bit register or memory with 64-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg64_rm64(reg64: GPR, rm64: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x3B], rm64, reg64) }
}
