//! This module contains the encoders for the `cpuid` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// CPU identification.
///
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[inline]
pub const unsafe fn encode() -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::zo::encode([0x0F, 0xA2]) }
}
