//! This module contains the encoders for the `int` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Generate software interrupt with vector specified by immediate byte.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm8(imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm8([0xCD], imm8) }
}

/// Generate debug trap. More or less equivalent to `int 1`.
///
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[inline]
pub const unsafe fn encode_1() -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::zo::encode([0xF1]) }
}

/// Generate breakpoint trap. More or less equivalent to `int 3`.
///
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[inline]
pub const unsafe fn encode_3() -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::zo::encode([0xCC]) }
}
