//! This module contains the encoders for the `jmp` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Short jump to RIP-relative address. Takes 2 bytes only.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm8(imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm8([0xEB], imm8) }
}

/// Long jump to RIP-relative address. Takes 5 bytes.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm32([0xE9], imm32) }
}

/// Jump to 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64(rm64: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::m::encode_gpr_or_memory([0xFF], 0x04, rm64, false, false) }
}
