//! This module contains the encoders for the `lea` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Load effective address from memory into 16-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg16_mem64(reg16: GPR, mem64: Memory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode_mem([0x8D], mem64, reg16) }
}

/// Load effective address from memory into 32-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg32_mem64(reg32: GPR, mem64: Memory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode_mem([0x8D], mem64, reg32) }
}

/// Load effective address from memory into 64-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg64_mem64(reg64: GPR, mem64: Memory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode_mem([0x8D], mem64, reg64) }
}
