//! This module contains the encoders for the `lock` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Lock prefix used for atomic operations.
///
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[inline]
pub const unsafe fn encode() -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::zo::encode([0xF0]) }
}
