//! This module contains the encoders for the `X86_64` instruction set.

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

pub mod add;
pub mod call;
pub mod cmp;
pub mod cpuid;
pub mod int;
pub mod jcc;
pub mod jmp;
pub mod lea;
pub mod lock;
pub mod mov;
pub mod nop;
pub mod pop;
pub mod push;
pub mod ret;
pub mod sub;
pub mod syscall;
pub mod sysenter;
pub mod xor;
