//! This module contains the encoders for the `mov` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Move 8-bit immediate to 8-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm8_imm8(rm8: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm8_imm8([0xC6], 0x00, rm8, imm8) }
}

/// Move 16-bit immediate to 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_imm16(rm16: GPROrMemory, imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm16_imm16([0xC7], 0x00, rm16, imm16) }
}

/// Move 32-bit immediate to 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_imm32(rm32: GPROrMemory, imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm32_imm32([0xC7], 0x00, rm32, imm32) }
}

/// Move 32-bit immediate to 64-bit register or memory, sign extended.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_imm32(rm64: GPROrMemory, imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm64_imm32([0xC7], 0x00, rm64, imm32) }
}

/// Move 8-bit immediate to 8-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg8_imm8(reg8: GPR, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::oi::encode_reg8_imm8(0xB0, reg8, imm8) }
}

/// Move 16-bit immediate to 16-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg16_imm16(reg16: GPR, imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::oi::encode_reg16_imm16(0xB8, reg16, imm16) }
}

/// Move 32-bit immediate to 32-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg32_imm32(reg32: GPR, imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::oi::encode_reg32_imm32(0xB8, reg32, imm32) }
}

/// Move 64-bit immediate to 64-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg64_imm64(reg64: GPR, imm64: Immediate64) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::oi::encode_reg64_imm64(0xB8, reg64, imm64) }
}

/// Move 8-bit register to 8-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm8_reg8(rm8: GPROrMemory, reg8: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x88], rm8, reg8) }
}

/// Move 16-bit register to 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_reg16(rm16: GPROrMemory, reg16: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x89], rm16, reg16) }
}

/// Move 32-bit register to 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_reg32(rm32: GPROrMemory, reg32: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x89], rm32, reg32) }
}

/// Move 64-bit register to 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_reg64(rm64: GPROrMemory, reg64: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x89], rm64, reg64) }
}

/// Move 8-bit register or memory to 8-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg8_rm8(reg8: GPR, rm8: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x8A], rm8, reg8) }
}

/// Move 16-bit register or memory to 16-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg16_rm16(reg16: GPR, rm16: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x8B], rm16, reg16) }
}

/// Move 32-bit register or memory to 32-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg32_rm32(reg32: GPR, rm32: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x8B], rm32, reg32) }
}

/// Move 64-bit register or memory to 64-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg64_rm64(reg64: GPR, rm64: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x8B], rm64, reg64) }
}
