//! This module contains the encoders for the `nop` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// No operation.
///
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[inline]
pub const unsafe fn encode() -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::zo::encode([0x90]) }
}

/// Represents length for NOP instruction. Internally this is `u8`
/// but with values in `0..=9` range.
#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy)]
#[repr(transparent)]
#[must_use]
pub struct NopLength {
    len: u8,
}

/// Represents the length out of range error. This happens whenever
/// the NOP instruction is outside of `0..=9` range.
#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy)]
#[repr(transparent)]
#[must_use]
pub struct NopLengthOutOfRange {
    phantom: core::marker::PhantomData<()>,
}

impl NopLength {
    /// Creates a new [`NopLength`].
    ///
    /// # Errors
    ///
    /// Returns [`NopLengthOutOfRange`] if `len > 9`.
    #[inline]
    pub const fn new(len: u8) -> Result<Self, NopLengthOutOfRange> {
        if len > 9 {
            return Err(NopLengthOutOfRange {
                phantom: core::marker::PhantomData,
            });
        }

        Ok(unsafe { Self::new_unchecked(len) })
    }

    /// Creates a new [`NopLength`].
    ///
    /// # Safety
    ///
    /// It is up to the caller to ensure that `len <= 9`.
    #[inline(always)]
    pub const unsafe fn new_unchecked(len: u8) -> Self {
        Self { len }
    }

    /// Returns the internal length.
    #[must_use]
    #[inline(always)]
    pub const fn as_u8(self) -> u8 {
        self.len
    }
}

impl TryFrom<u8> for NopLength {
    type Error = NopLengthOutOfRange;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<NopLength> for u8 {
    fn from(value: NopLength) -> Self {
        value.len
    }
}

/// No operation with a given length.
///
/// # Notes
///
/// * The [`encode_with_len(0)`][encode_with_len] call returns an empty instruction (of length 0).
/// * The [`encode_with_len(1)`][encode_with_len] call is equivalent to [`encode()`] call. Except
///   it is slightly less efficient.
/// * The [`encode_with_len(n)`][encode_with_len] call returns an instruction of length `n`.
///
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[allow(clippy::missing_panics_doc)]
pub const unsafe fn encode_with_len(len: NopLength) -> EncodedX86_64Instruction {
    use crate::partial_encoders::zo::encode;
    unsafe {
        match len.as_u8() {
            0 => EncodedX86_64Instruction::new(),
            1 => encode([0x90]),
            2 => encode([0x66, 0x90]),
            3 => encode([0x0F, 0x1F, 0x00]),
            4 => encode([0x0F, 0x1F, 0x40, 0x00]),
            5 => encode([0x0F, 0x1F, 0x44, 0x00, 0x00]),
            6 => encode([0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00]),
            7 => encode([0x0F, 0x1F, 0x80, 0x00, 0x00, 0x00, 0x00]),
            8 => encode([0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00]),
            9 => encode([0x66, 0x0F, 0x1F, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00]),
            _ => panic!("Invalid length for encode_with_len call. Expected u8 in 1..=9 range."),
        }
    }
}
