//! This module contains the encoders for the `pop` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Pop 64-bit value from the stack into register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64(rm64: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::m::encode_gpr_or_memory([0x8F], 0x00, rm64, false, false) }
}

/// Pop 64-bit value from the stack into register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg64(reg64: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::o::encode([0x58], reg64) }
}
