//! This module contains the encoders for the `push` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Push 64-bit register or memory onto the stack.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64(rm64: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::m::encode_gpr_or_memory([0xFF], 0x06, rm64, false, false) }
}

/// Push 64-bit register onto the stack.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg64(reg64: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::o::encode([0x50], reg64) }
}

/// Push 8-bit immediate onto the stack (sign-extended).
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm8(imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm8([0x6A], imm8) }
}

/// Push 16-bit immediate onto the stack (sign-extended).
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm16(imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm16_oso([0x68], imm16) }
}

/// Push 32-bit immediate onto the stack (sign-extended).
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm32([0x68], imm32) }
}
