//! This module contains the encoders for the `ret` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Return to calling procedure.
///
/// # Safety
///
/// This function is safe to call. It is marked as unsafe for consistency with other encoders.
#[inline]
pub const unsafe fn encode() -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::zo::encode([0xC3]) }
}

/// Pop [16-bit immediate] bytes from stack and return to calling procedure.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_imm16(imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm16([0xC2], imm16) }
}
