//! This module contains the encoders for the `xor` instruction group.
#![allow(unused_imports)]

// ** This file is automatically generated from x86.yaml schema. Do not modify! **

use crate::models::{
    EncodedX86_64Instruction, GPR, GPROrMemory, Immediate8, Immediate16, Immediate32, Immediate64, Memory, Offset,
    Scale, Size,
};

/// Bitwise XOR 8-bit immediate with AL register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_al_imm8(imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm8([0x34], imm8) }
}

/// Bitwise XOR 16-bit immediate with AX register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_ax_imm16(imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm16_oso([0x35], imm16) }
}

/// Bitwise XOR 32-bit immediate with EAX register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_eax_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm32([0x35], imm32) }
}

/// Bitwise XOR 32-bit immediate with RAX register (sign-extended to 64 bits).
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rax_imm32(imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::i::encode_imm32_rexw([0x35], imm32) }
}

/// Bitwise XOR 8-bit immediate with 8-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm8_imm8(rm8: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm8_imm8([0x80], 0x06, rm8, imm8) }
}

/// Bitwise XOR 16-bit immediate with 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_imm16(rm16: GPROrMemory, imm16: Immediate16) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm16_imm16([0x81], 0x06, rm16, imm16) }
}

/// Bitwise XOR 32-bit immediate with 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_imm32(rm32: GPROrMemory, imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm32_imm32([0x81], 0x06, rm32, imm32) }
}

/// Bitwise XOR 32-bit immediate with 64-bit register or memory (sign-extended to 64 bits).
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_imm32(rm64: GPROrMemory, imm32: Immediate32) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm64_imm32([0x81], 0x06, rm64, imm32) }
}

/// Bitwise XOR 8-bit immediate (sign-extended) with 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_imm8(rm16: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm16_imm8([0x83], 0x06, rm16, imm8) }
}

/// Bitwise XOR 8-bit immediate (sign-extended) with 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_imm8(rm32: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm32_imm8([0x83], 0x06, rm32, imm8) }
}

/// Bitwise XOR 8-bit immediate (sign-extended) with 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_imm8(rm64: GPROrMemory, imm8: Immediate8) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mi::encode_rm64_imm8([0x83], 0x06, rm64, imm8) }
}

/// Bitwise XOR 8-bit register with 8-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm8_reg8(rm8: GPROrMemory, reg8: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x30], rm8, reg8) }
}

/// Bitwise XOR 16-bit register with 16-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm16_reg16(rm16: GPROrMemory, reg16: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x31], rm16, reg16) }
}

/// Bitwise XOR 32-bit register with 32-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm32_reg32(rm32: GPROrMemory, reg32: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x31], rm32, reg32) }
}

/// Bitwise XOR 64-bit register with 64-bit register or memory.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_rm64_reg64(rm64: GPROrMemory, reg64: GPR) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x31], rm64, reg64) }
}

/// Bitwise XOR 8-bit register or memory with 8-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg8_rm8(reg8: GPR, rm8: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x32], rm8, reg8) }
}

/// Bitwise XOR 16-bit register or memory with 16-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg16_rm16(reg16: GPR, rm16: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x33], rm16, reg16) }
}

/// Bitwise XOR 32-bit register or memory with 32-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg32_rm32(reg32: GPR, rm32: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x33], rm32, reg32) }
}

/// Bitwise XOR 64-bit register or memory with 64-bit register.
///
/// # Safety
///
/// It is the caller's responsibility to ensure that the operands are valid.
/// Otherwise the behavior is undefined.
#[inline]
pub const unsafe fn encode_reg64_rm64(reg64: GPR, rm64: GPROrMemory) -> EncodedX86_64Instruction {
    unsafe { crate::partial_encoders::mr::encode([0x33], rm64, reg64) }
}
